version: 2

defaults: &defaults
  docker:
    # Use one of the official Cypress images
    - image: cypress/base:6
      environment:
        # This enables terminal colors
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}
          paths: node_modules
      - persist_to_workspace:
          root: /root
          # We need to save the fully-built application for the test phase
          # We also need to save the Cypress binary, which gets installed to /root/.cache  
          paths:
            - ./project
            - .cache
  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: /root
      - run:
          command: yarn start
          # Start the HTTP server in the background
          background: true
      - run: yarn test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
