version: 2

defaults: &defaults
  docker:
    - image: cypress/base:6
      environment:
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}
          paths: node_modules
      - run: ls -al
      - run: pwd
      - persist_to_workspace:
          root: /root
          paths:
            - ./project
            - .cache
  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: /root
      - run: ls -al
      - run: pwd
      - run:
          command: yarn start
          background: true
      - run: yarn test
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
