version: 2
jobs:
  build:
    docker:
      # TODO: Use a base image that I uploaded myself
      - image: cypress/base:8
    working_directory: ~/repo
    parallelism: 2
    steps:
      - checkout
      - run: yarn install
      - run:
          command: yarn start
          background: true
      - run: yarn test
