version: 2
jobs:
  build:
    docker:
      # TODO: Use a base image that I uploaded myself
      - image: cypress/base:8
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: yarn start
          background: true
      - run: yarn test
