version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          root: .
          paths: .
  test:
    parallelism: 2
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace
	        at: .
      - run:
          command: yarn start
          background: true
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
