version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          key: v1-deps-{{ .Branch }}
          key: v1-deps
      - run: yarn install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - .cache
      - persist_to_workspace:
          root: .
          paths: .
  test:
    parallelism: 2
    docker:
      - image: cypress/base:8
    steps:
      - attach_workspace:
          at: .
      - run: ls -al
      - run: pwd
      - run:
          command: yarn start
          background: true
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
